//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineDemonstrator.MobileClient.Localization {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("OnlineDemonstrator.MobileClient.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AddButton {
            get {
                return ResourceManager.GetString("AddButton", resourceCulture);
            }
        }
        
        internal static string EverythingFromThisDemo {
            get {
                return ResourceManager.GetString("EverythingFromThisDemo", resourceCulture);
            }
        }
        
        internal static string OtherDemonstrations {
            get {
                return ResourceManager.GetString("OtherDemonstrations", resourceCulture);
            }
        }
        
        internal static string MapTab {
            get {
                return ResourceManager.GetString("MapTab", resourceCulture);
            }
        }
        
        internal static string SettingsTab {
            get {
                return ResourceManager.GetString("SettingsTab", resourceCulture);
            }
        }
        
        internal static string YourName {
            get {
                return ResourceManager.GetString("YourName", resourceCulture);
            }
        }
        
        internal static string TitleCreator {
            get {
                return ResourceManager.GetString("TitleCreator", resourceCulture);
            }
        }
        
        internal static string MessageCreator {
            get {
                return ResourceManager.GetString("MessageCreator", resourceCulture);
            }
        }
        
        internal static string PosterAddedSuccessfully {
            get {
                return ResourceManager.GetString("PosterAddedSuccessfully", resourceCulture);
            }
        }
        
        internal static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        internal static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        internal static string IAgreeButton {
            get {
                return ResourceManager.GetString("IAgreeButton", resourceCulture);
            }
        }
        
        internal static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        internal static string PrivacyPolicyLink {
            get {
                return ResourceManager.GetString("PrivacyPolicyLink", resourceCulture);
            }
        }
        
        internal static string LicenseLink {
            get {
                return ResourceManager.GetString("LicenseLink", resourceCulture);
            }
        }
        
        internal static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        internal static string YourReportHasBeenSentSuccessfully {
            get {
                return ResourceManager.GetString("YourReportHasBeenSentSuccessfully", resourceCulture);
            }
        }
        
        internal static string CallDoNotWait {
            get {
                return ResourceManager.GetString("CallDoNotWait", resourceCulture);
            }
        }
        
        internal static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        internal static string CommentPlaceholder {
            get {
                return ResourceManager.GetString("CommentPlaceholder", resourceCulture);
            }
        }
        
        internal static string PrivacyDisplayMessage {
            get {
                return ResourceManager.GetString("PrivacyDisplayMessage", resourceCulture);
            }
        }
        
        internal static string DearUsers {
            get {
                return ResourceManager.GetString("DearUsers", resourceCulture);
            }
        }
        
        internal static string NudityOrSexualActivity {
            get {
                return ResourceManager.GetString("NudityOrSexualActivity", resourceCulture);
            }
        }
        
        internal static string HateSpeechOrSymbols {
            get {
                return ResourceManager.GetString("HateSpeechOrSymbols", resourceCulture);
            }
        }
        
        internal static string ViolenceOrDangerousOrganizations {
            get {
                return ResourceManager.GetString("ViolenceOrDangerousOrganizations", resourceCulture);
            }
        }
        
        internal static string SaleOfIllegalOrRegularGoods {
            get {
                return ResourceManager.GetString("SaleOfIllegalOrRegularGoods", resourceCulture);
            }
        }
        
        internal static string BullyingOrHarassment {
            get {
                return ResourceManager.GetString("BullyingOrHarassment", resourceCulture);
            }
        }
        
        internal static string IntellectualPropertyViolation {
            get {
                return ResourceManager.GetString("IntellectualPropertyViolation", resourceCulture);
            }
        }
        
        internal static string SuicideOrSelfInjury {
            get {
                return ResourceManager.GetString("SuicideOrSelfInjury", resourceCulture);
            }
        }
        
        internal static string ScamOrFraud {
            get {
                return ResourceManager.GetString("ScamOrFraud", resourceCulture);
            }
        }
        
        internal static string FalseInformation {
            get {
                return ResourceManager.GetString("FalseInformation", resourceCulture);
            }
        }
        
        internal static string ConfirmAction {
            get {
                return ResourceManager.GetString("ConfirmAction", resourceCulture);
            }
        }
        
        internal static string ConfirmActionYes {
            get {
                return ResourceManager.GetString("ConfirmActionYes", resourceCulture);
            }
        }
        
        internal static string ConfirmActionNo {
            get {
                return ResourceManager.GetString("ConfirmActionNo", resourceCulture);
            }
        }
        
        internal static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        internal static string MessageTitleAreRequired {
            get {
                return ResourceManager.GetString("MessageTitleAreRequired", resourceCulture);
            }
        }
        
        internal static string ForbiddenSymbols {
            get {
                return ResourceManager.GetString("ForbiddenSymbols", resourceCulture);
            }
        }
        
        internal static string Follow {
            get {
                return ResourceManager.GetString("Follow", resourceCulture);
            }
        }
        
        internal static string NumberOfParticipants {
            get {
                return ResourceManager.GetString("NumberOfParticipants", resourceCulture);
            }
        }
        
        internal static string NoDemonstrations {
            get {
                return ResourceManager.GetString("NoDemonstrations", resourceCulture);
            }
        }
        
        internal static string ExpDemonstrationInDays {
            get {
                return ResourceManager.GetString("ExpDemonstrationInDays", resourceCulture);
            }
        }
        
        internal static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        internal static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        internal static string DaysMoreThenFour {
            get {
                return ResourceManager.GetString("DaysMoreThenFour", resourceCulture);
            }
        }
        
        internal static string NotificationError {
            get {
                return ResourceManager.GetString("NotificationError", resourceCulture);
            }
        }
    }
}
